[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/PaulStoffregen/OneWire.git  ; v2.3.7 inkompatibel mit ESP-IDF 5.x; v2.3.8 bug; git-master hat den Fix
    milesburton/DallasTemperature@4.0.4
    knolleary/PubSubClient@2.8
